theme: jekyll-theme-architect
title: "{Dev} Ramstein"
description: Software Development Club
show_downloads: ["true"]
github:
  sidebar: "Facebook Group"
  zip_url: https://www.facebook.com/groups/devramstein/
  
